# Generated by Django 3.1.4 on 2020-12-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Organization_Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
