# Generated by Django 3.1.4 on 2020-12-18 11:07

from django.db import migrations, models
import lionsclub.models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsclub', '0002_organization_organization_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Date_Of_Establishment',
            field=models.DateField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Organization_Image',
            field=models.ImageField(blank=True, null=True, upload_to=lionsclub.models.upload_path),
        ),
    ]
