# Generated by Django 3.1.4 on 2020-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsclub', '0003_auto_20201218_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Date_Of_Establishment',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
